name: "Helm and Kubectl on EKS (with aws-iam-authenticator)"
description: "Authenticates on EKS clusters using aws-iam-authenticator and runs helm and kubectl commands"
branding:
  icon: "anchor"
  color: "blue"
inputs:
  command:
    description: "Your command (kubectl or helm)"
    required: true
  plugins:
    description: "Comma-separated URLs for the Helm Plugins you need installed"
    required: false
outputs:
  result:
    description: "Output returned by your Helm or kubectl command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
